/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hbsi_dtd_test_MyActivity */

#ifndef _Included_hbsi_dtd_test_MyActivity
#define _Included_hbsi_dtd_test_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hbsi_dtd_test_MyActivity
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hbsi_dtd_test_MyActivity_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     hbsi_dtd_test_MyActivity
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_hbsi_dtd_test_MyActivity_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hbsi_dtd_test_MyActivity
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hbsi_dtd_test_MyActivity_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hbsi_dtd_test_MyActivity
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_hbsi_dtd_test_MyActivity_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
