/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hbsi_dtd_test_MyActivity */

#ifndef _Included_hbsi_dtd_opengles_MyRenderer
#define _Included_hbsi_dtd_opengles_MyRenderer
#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT void JNICALL Java_hbsi_dtd_opengles_MyRenderer_glinit(JNIEnv *env, jobject thisz);
	JNIEXPORT void JNICALL Java_hbsi_dtd_opengles_MyRenderer_changeSize(JNIEnv *env, jobject thisz,jint w, jint h);
	JNIEXPORT void JNICALL Java_hbsi_dtd_opengles_MyRenderer_drawFrame(JNIEnv *env, jobject thisz);


	static float last_timer = 0;//记录上次的系统时间
	static float Angle = 0;//旋转的角度
	void display(void);//opengl es 的主要绘制代码在这个里面

#ifdef __cplusplus
}
#endif
#endif
